[package]
name = "loom-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
loom-core = { path = "../crates/loom-core" }
loom-hir = { path = "../crates/loom-hir" }
loom-interpreter = { path = "../crates/loom-interpreter" }
loom-lowering = { path = "../crates/loom-lowering" }
loom-mir = { path = "../crates/loom-mir" }
loom-sema = { path = "../crates/loom-sema" }
loom-syntax = { path = "../crates/loom-syntax" }

[workspace]
members = ["."]

[[bin]]
name = "syntax"
path = "fuzz_targets/syntax.rs"
test = false
doc = false
bench = false

[[bin]]
name = "artifact"
path = "fuzz_targets/artifact.rs"
test = false
doc = false
bench = false

[[bin]]
name = "semantics"
path = "fuzz_targets/semantics.rs"
test = false
doc = false
bench = false
