[package]
name = "loom-sema"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
loom-core.workspace = true
loom-hir.workspace = true
serde.workspace = true
loom-syntax.workspace = true

[lints]
workspace = true
