[package]
name = "loom-codegen-ir"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
loom-core.workspace = true
loom-mir.workspace = true
serde.workspace = true

[dev-dependencies]
loom-hir.workspace = true
loom-lowering.workspace = true
loom-sema.workspace = true
loom-syntax.workspace = true
serde_json.workspace = true
wait-timeout.workspace = true

[lints]
workspace = true
