[package]
name = "loom-tls"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
loom-runtime = { path = "../runtime" }
rustls.workspace = true
rustls-pemfile.workspace = true
webpki-roots = "=1.0.9"

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
all = "warn"
